service: cadastro-pacientes
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x


  stage: dev
  region: us-east-1


functions:
  listarPacientes:
    handler: handler.listarPacientes
    events:
      - http:
          path: pacientes
          method: get
          cors: true
  
  obterPaciente:
    handler: handler.obterPaciente
    events:
      - http:
          path: /pacientes/{pacienteId}
          method: get
          cors: true
